//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_Code_2022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_Code_2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5474
        ///4920
        ///5381
        ///8650
        ///11617
        ///7193
        ///8161
        ///
        ///10747
        ///5855
        ///13827
        ///6294
        ///13437
        ///8125
        ///
        ///6913
        ///6443
        ///3431
        ///5357
        ///1579
        ///3590
        ///4471
        ///4971
        ///4055
        ///4937
        ///2514
        ///1679
        ///2917
        ///
        ///4203
        ///4433
        ///8798
        ///5838
        ///2031
        ///8765
        ///5107
        ///6055
        ///2482
        ///6266
        ///
        ///4646
        ///4705
        ///5183
        ///1707
        ///3676
        ///2042
        ///4140
        ///3321
        ///1899
        ///3055
        ///3327
        ///3944
        ///3879
        ///2981
        ///
        ///59238
        ///
        ///11748
        ///22005
        ///
        ///6389
        ///4630
        ///1443
        ///14530
        ///9588
        ///
        ///10578
        ///8843
        ///10344
        ///6289
        ///10444
        ///7615
        ///9510
        ///
        ///9351
        ///3942
        ///5896
        ///4692
        ///10110
        ///4125
        ///1161
        ///8261
        ///
        ///22239
        ///
        ///5485
        ///1528
        ///1288
        ///4749
        ///3742
        ///586 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay1 {
            get {
                return ResourceManager.GetString("DataDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Z
        ///A X
        ///C X
        ///C X
        ///C Z
        ///C X
        ///C X
        ///A Z
        ///C X
        ///B Z
        ///B Z
        ///C X
        ///A X
        ///C X
        ///C X
        ///C X
        ///C Y
        ///C X
        ///C Z
        ///C X
        ///C X
        ///C X
        ///C X
        ///C X
        ///C Z
        ///C X
        ///C X
        ///A X
        ///C X
        ///B Y
        ///A X
        ///B X
        ///A Z
        ///C X
        ///B Y
        ///A X
        ///C Z
        ///C X
        ///C Z
        ///A X
        ///A Y
        ///B Z
        ///A Z
        ///C X
        ///A Z
        ///A Z
        ///A Y
        ///C Y
        ///A Y
        ///A Z
        ///C X
        ///A Y
        ///B Y
        ///A Z
        ///B Y
        ///C Z
        ///A X
        ///C X
        ///C Z
        ///B Z
        ///C X
        ///B Y
        ///C X
        ///A Z
        ///C X
        ///A X
        ///C X
        ///C X
        ///A Z
        ///B Z
        ///C X
        ///C X
        ///C Z
        ///C X
        ///B X
        ///C X
        ///A Z
        ///A X
        ///A Y
        ///A Y
        ///A Z
        ///C X
        ///C Z
        ///C X
        ///B Y
        ///C X
        ///C X
        ///A X
        ///A X
        ///C Z
        ///C X
        ///B X
        ///C Z
        ///C X
        ///C X
        ///C X
        ///B Z
        ///B Y
        ///A Z
        ///C X
        ///A Z
        ///C X
        ///C  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay2 {
            get {
                return ResourceManager.GetString("DataDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gvNbShZZgQfWdQhdPQmggLTFLwmwjFqjVVgM
        ///CsJnHllcsnnnnJrGRnRwPPLVmFLHLBjFFVHmPT
        ///JlnCtctJnJDcJlDCRpPrSSQWfphzWZfbZSvfNfbS
        ///WjvRSdSQjvpjWzNlnZlNZqCCMzZZ
        ///nJtJsbctPBPwLNcDZNNGLClC
        ///tsFJHBgJwgJbnvSHHWVWHhVhpQ
        ///zRzPhCCSHVZzfGHZ
        ///qBsWBpqBwBcvqqWgdfZrprdggPHHVZ
        ///WWmvwvBbnWmnwvWcbmWWnqNCRSDRRSSjjSDbPJbRjClLhC
        ///rQrznfHHhrHzllzlzTGcJgtJ
        ///jhhjjSZVPWVZvSFtTttLTglgFtvm
        ///dqSCqVWdbDSSVqbVVSqhNdrnpnCnfsnnwfnsRpMpBMrf
        ///rTnvrSSHvHtnDQVDtfmW
        ///ZjCglhcCJschpZbZgbtGmRtbGmwtQtbmtN
        ///FFZCghFJhlslFpjcdFTPLHHmrqTMTdzBLHLH
        ///WzDfrDwwDCCD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay3 {
            get {
                return ResourceManager.GetString("DataDay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-7,8-42
        ///2-95,2-94
        ///10-54,33-90
        ///23-24,24-40
        ///1-48,12-47
        ///9-27,9-26
        ///24-33,25-45
        ///16-26,15-26
        ///28-38,38-40
        ///26-27,27-48
        ///39-97,20-96
        ///21-73,21-73
        ///15-28,27-63
        ///6-91,91-91
        ///52-80,81-96
        ///18-99,17-83
        ///90-97,91-96
        ///9-91,10-82
        ///8-97,9-99
        ///67-73,66-74
        ///48-63,11-63
        ///35-90,36-92
        ///9-94,1-9
        ///7-10,9-95
        ///19-46,18-47
        ///41-82,48-83
        ///35-81,36-84
        ///5-92,2-91
        ///54-94,53-94
        ///12-27,26-81
        ///17-26,8-14
        ///18-84,9-85
        ///49-64,65-82
        ///39-84,38-83
        ///20-65,64-66
        ///16-95,16-80
        ///31-36,37-78
        ///19-71,19-19
        ///12-90,11-89
        ///12-47,11-48
        ///10-11,10-74
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay4 {
            get {
                return ResourceManager.GetString("DataDay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [J]             [F] [M]            
        ///[Z] [F]     [G] [Q] [F]            
        ///[G] [P]     [H] [Z] [S] [Q]        
        ///[V] [W] [Z] [P] [D] [G] [P]        
        ///[T] [D] [S] [Z] [N] [W] [B] [N]    
        ///[D] [M] [R] [J] [J] [P] [V] [P] [J]
        ///[B] [R] [C] [T] [C] [V] [C] [B] [P]
        ///[N] [S] [V] [R] [T] [N] [G] [Z] [W]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 2 from 4 to 6
        ///move 1 from 9 to 5
        ///move 3 from 2 to 4
        ///move 8 from 4 to 7
        ///move 2 from 9 to 7
        ///move 3 from 8 to 3
        ///move 2 from 1 to 2
        ///move 5 from 7 to 9
        ///move 1 from 9 to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay5 {
            get {
                return ResourceManager.GetString("DataDay5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdhccdbdggfjjgssjzjzggjnjpnpbbzbnzzflfjfnfrrpvrvbrvvrvggvlvnnbrnrcncsnndbndbnndbdndfdrdvrvvndvvbggnrrnbrnntffgttwzwnnmvmcvvhsstzzlnlwlttbzzpnpmnnjvjnntmnmfftwwrfwrwswmmfrrfrrgbrbffwvvshvhrhmhththbbmqbmqqlslhssrmmqdmmjtmtmjtmjtttnwnvwvqwqjjnbbbdbqbnbpnbnllglcglcgcdczdznnqhhfthtmtlldqlqrrmddrldlzdllvddjcddqfqbqsbqqnllwppqpqzzrbbdppzsppjdpdqpdqdfqfrrwbwrwwqcqcsqsvvpbvbbztzptzzpccdtdhdffvqvcvzzmwzwddjfdffplplqlvlmmmvggpmpvpddpbptplpvlplvpvvnrvnnbqqqjhhwfhwfhwhqhmmpphqpqvppfzpzjzddgzzwffjmjggwhwwnnmlmpmmhcmcpcrc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay6 {
            get {
                return ResourceManager.GetString("DataDay6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir bqc
        ///dir mwmlf
        ///dir ngn
        ///143562 nrwjb
        ///78449 qqvdcclf
        ///dir qrnm
        ///dir smfzmmhc
        ///116085 tvrms
        ///dir vrdrsj
        ///$ cd bqc
        ///$ ls
        ///5693 qqvdcclf
        ///$ cd ..
        ///$ cd mwmlf
        ///$ ls
        ///dir cmfphpc
        ///dir lqqshq
        ///dir mwmlf
        ///dir rlf
        ///dir smfzmmhc
        ///$ cd cmfphpc
        ///$ ls
        ///235620 tprth.gjn
        ///82743 vrdrsj.fbl
        ///$ cd ..
        ///$ cd lqqshq
        ///$ ls
        ///94188 crswqlvd.nsj
        ///dir dttthls
        ///60078 lbsfsspm
        ///dir lqp
        ///74624 nrwjb
        ///247709 tjhcqw.wrq
        ///267693 tvrms
        ///dir zshrcgfn
        ///$ cd dttthls
        ///$ ls
        ///109072 nrwjb
        ///31512 qqvdcclf
        ///$ cd ..
        ///$ cd lqp
        ///$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay7 {
            get {
                return ResourceManager.GetString("DataDay7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///2000
        ///3000
        ///
        ///4000
        ///
        ///5000
        ///6000
        ///
        ///7000
        ///8000
        ///9000
        ///
        ///10000.
        /// </summary>
        internal static string ExampleDataDay1 {
            get {
                return ResourceManager.GetString("ExampleDataDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Y
        ///B X
        ///C Z.
        /// </summary>
        internal static string ExampleDataDay2 {
            get {
                return ResourceManager.GetString("ExampleDataDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vJrwpWtwJgWrhcsFMMfFFhFp
        ///jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
        ///PmmdzqPrVvPwwTWBwg
        ///wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
        ///ttgJtRGJQctTZtZT
        ///CrZsJsPPZsGzwwsLwLmpwMDw.
        /// </summary>
        internal static string ExampleDataDay3 {
            get {
                return ResourceManager.GetString("ExampleDataDay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-4,6-8
        ///2-3,4-5
        ///5-7,7-9
        ///2-8,3-7
        ///6-6,4-6
        ///2-6,4-8.
        /// </summary>
        internal static string ExampleDataDay4 {
            get {
                return ResourceManager.GetString("ExampleDataDay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [D]    
        ///[N] [C]    
        ///[Z] [M] [P]
        /// 1   2   3 
        ///
        ///move 1 from 2 to 1
        ///move 3 from 1 to 3
        ///move 2 from 2 to 1
        ///move 1 from 1 to 2.
        /// </summary>
        internal static string ExampleDataDay5 {
            get {
                return ResourceManager.GetString("ExampleDataDay5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bvwbjplbgvbhsrlpgdmjqwftvncz.
        /// </summary>
        internal static string ExampleDataDay6 {
            get {
                return ResourceManager.GetString("ExampleDataDay6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir a
        ///14848514 b.txt
        ///8504156 c.dat
        ///dir d
        ///$ cd a
        ///$ ls
        ///dir e
        ///29116 f
        ///2557 g
        ///62596 h.lst
        ///$ cd e
        ///$ ls
        ///584 i
        ///$ cd ..
        ///$ cd ..
        ///$ cd d
        ///$ ls
        ///4060174 j
        ///8033020 d.log
        ///5626152 d.ext
        ///7214296 k.
        /// </summary>
        internal static string ExampleDataDay7 {
            get {
                return ResourceManager.GetString("ExampleDataDay7", resourceCulture);
            }
        }
    }
}
