//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_Code_2022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_Code_2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5474
        ///4920
        ///5381
        ///8650
        ///11617
        ///7193
        ///8161
        ///
        ///10747
        ///5855
        ///13827
        ///6294
        ///13437
        ///8125
        ///
        ///6913
        ///6443
        ///3431
        ///5357
        ///1579
        ///3590
        ///4471
        ///4971
        ///4055
        ///4937
        ///2514
        ///1679
        ///2917
        ///
        ///4203
        ///4433
        ///8798
        ///5838
        ///2031
        ///8765
        ///5107
        ///6055
        ///2482
        ///6266
        ///
        ///4646
        ///4705
        ///5183
        ///1707
        ///3676
        ///2042
        ///4140
        ///3321
        ///1899
        ///3055
        ///3327
        ///3944
        ///3879
        ///2981
        ///
        ///59238
        ///
        ///11748
        ///22005
        ///
        ///6389
        ///4630
        ///1443
        ///14530
        ///9588
        ///
        ///10578
        ///8843
        ///10344
        ///6289
        ///10444
        ///7615
        ///9510
        ///
        ///9351
        ///3942
        ///5896
        ///4692
        ///10110
        ///4125
        ///1161
        ///8261
        ///
        ///22239
        ///
        ///5485
        ///1528
        ///1288
        ///4749
        ///3742
        ///586 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay1 {
            get {
                return ResourceManager.GetString("DataDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Z
        ///A X
        ///C X
        ///C X
        ///C Z
        ///C X
        ///C X
        ///A Z
        ///C X
        ///B Z
        ///B Z
        ///C X
        ///A X
        ///C X
        ///C X
        ///C X
        ///C Y
        ///C X
        ///C Z
        ///C X
        ///C X
        ///C X
        ///C X
        ///C X
        ///C Z
        ///C X
        ///C X
        ///A X
        ///C X
        ///B Y
        ///A X
        ///B X
        ///A Z
        ///C X
        ///B Y
        ///A X
        ///C Z
        ///C X
        ///C Z
        ///A X
        ///A Y
        ///B Z
        ///A Z
        ///C X
        ///A Z
        ///A Z
        ///A Y
        ///C Y
        ///A Y
        ///A Z
        ///C X
        ///A Y
        ///B Y
        ///A Z
        ///B Y
        ///C Z
        ///A X
        ///C X
        ///C Z
        ///B Z
        ///C X
        ///B Y
        ///C X
        ///A Z
        ///C X
        ///A X
        ///C X
        ///C X
        ///A Z
        ///B Z
        ///C X
        ///C X
        ///C Z
        ///C X
        ///B X
        ///C X
        ///A Z
        ///A X
        ///A Y
        ///A Y
        ///A Z
        ///C X
        ///C Z
        ///C X
        ///B Y
        ///C X
        ///C X
        ///A X
        ///A X
        ///C Z
        ///C X
        ///B X
        ///C Z
        ///C X
        ///C X
        ///C X
        ///B Z
        ///B Y
        ///A Z
        ///C X
        ///A Z
        ///C X
        ///C  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay2 {
            get {
                return ResourceManager.GetString("DataDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///2000
        ///3000
        ///
        ///4000
        ///
        ///5000
        ///6000
        ///
        ///7000
        ///8000
        ///9000
        ///
        ///10000.
        /// </summary>
        internal static string ExampleDataDay1 {
            get {
                return ResourceManager.GetString("ExampleDataDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Y
        ///B X
        ///C Z.
        /// </summary>
        internal static string ExampleDataDay2 {
            get {
                return ResourceManager.GetString("ExampleDataDay2", resourceCulture);
            }
        }
    }
}
